name = "WbThirdLife"
author = "Chugabunga"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b78dfe7ce0bd3d940ef64ee86c92088f117748369d4e7064e26fb940e1fe5b2e"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
