name = "WbThirdLife"
author = "Chugabunga"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7736878da7ba4eef6fd279585e7e3c63d5b477ee19ffde2380c7b4cc3b04686"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
